development:
  sessions:
    default:
      database: engine_manager_dev
      hosts:
        - localhost:27017
test:
  sessions:
    default:
      database: engine_manager_test
      hosts:
        - localhost:27017